"""init 17 tables MVP

Revision ID: 1fc1afa9e06f
Revises: 
Create Date: 2026-09-30 17:21:56.211544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc1afa9e06f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('drug_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_vi', sa.Text(), nullable=False),
    sa.Column('base_name', sa.Text(), nullable=False),
    sa.Column('route_variant', sa.Text(), nullable=False),
    sa.Column('drugbank_id', sa.Text(), nullable=True),
    sa.Column('atc_code', sa.Text(), nullable=True),
    sa.Column('drug_type', sa.Text(), nullable=True),
    sa.Column('in_vn', sa.Boolean(), nullable=False),
    sa.Column('n_products_valid', sa.Integer(), nullable=False),
    sa.Column('n_interactions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('drug_id', name=op.f('pk_drugs'))
    )
    op.create_index('ix_drugs_atc', 'drugs', ['atc_code'], unique=False)
    op.create_index('ix_drugs_base_name', 'drugs', ['base_name'], unique=False)
    op.create_index(op.f('ix_drugs_in_vn'), 'drugs', ['in_vn'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('highest_severity_vi', sa.Text(), nullable=True),
    sa.Column('checks_count', sa.Integer(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_table('sources',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_sources'))
    )
    op.create_table('aliases',
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('drug_id', sa.String(), nullable=False),
    sa.Column('alias_type', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('drug_name', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('ok','suggest')", name=op.f('ck_aliases_ck_alias_status')),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], name=op.f('fk_aliases_drug_id_drugs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_aliases_source_id_sources')),
    sa.PrimaryKeyConstraint('alias', 'drug_id', 'source_id', name=op.f('pk_aliases'))
    )
    op.create_index('ix_aliases_drug', 'aliases', ['drug_id'], unique=False)
    op.create_table('ara_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('victim_drug_ids', sa.JSON(), nullable=False),
    sa.Column('victim_form', sa.Text(), nullable=False),
    sa.Column('victim_is_combination', sa.Boolean(), nullable=False),
    sa.Column('ara_class', sa.Text(), nullable=True),
    sa.Column('ara_drug_ids', sa.JSON(), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('route_scope', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_ara_interactions_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ara_interactions'))
    )
    op.create_table('checks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prescription_id', sa.String(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('meds_snapshot', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('max_severity', sa.Text(), nullable=True),
    sa.Column('steps_done', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_checks_prescription_id_prescriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checks'))
    )
    op.create_index(op.f('ix_checks_prescription_id'), 'checks', ['prescription_id'], unique=False)
    op.create_table('disease_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drug_id', sa.String(), nullable=True),
    sa.Column('disease', sa.Text(), nullable=True),
    sa.Column('mesh_id', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], name=op.f('fk_disease_interactions_drug_id_drugs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_disease_interactions_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disease_interactions'))
    )
    op.create_index(op.f('ix_disease_interactions_drug_id'), 'disease_interactions', ['drug_id'], unique=False)
    op.create_table('dosage_form_rules',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('drug_id', sa.String(), nullable=True),
    sa.Column('drug_route', sa.Text(), nullable=True),
    sa.Column('drug_form', sa.Text(), nullable=True),
    sa.Column('other_drug_id', sa.String(), nullable=False),
    sa.Column('other_route', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('effect_vi', sa.Text(), nullable=True),
    sa.Column('management_vi', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], name=op.f('fk_dosage_form_rules_drug_id_drugs')),
    sa.ForeignKeyConstraint(['other_drug_id'], ['drugs.drug_id'], name=op.f('fk_dosage_form_rules_other_drug_id_drugs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_dosage_form_rules_source_id_sources')),
    sa.PrimaryKeyConstraint('rule_id', 'other_drug_id', name=op.f('pk_dosage_form_rules'))
    )
    op.create_table('duplication_classes',
    sa.Column('class_name', sa.Text(), nullable=False),
    sa.Column('drug_id', sa.String(), nullable=False),
    sa.Column('drug_name', sa.Text(), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], name=op.f('fk_duplication_classes_drug_id_drugs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_duplication_classes_source_id_sources')),
    sa.PrimaryKeyConstraint('class_name', 'drug_id', name=op.f('pk_duplication_classes'))
    )
    op.create_table('fda_labels',
    sa.Column('label_set_id', sa.String(), nullable=False),
    sa.Column('effective_time', sa.Text(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('substances', sa.Text(), nullable=True),
    sa.Column('drug_ids', sa.JSON(), nullable=False),
    sa.Column('brand_names', sa.Text(), nullable=True),
    sa.Column('boxed_warning', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('drug_interactions', sa.Text(), nullable=True),
    sa.Column('dosage_forms_and_strengths', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_fda_labels_source_id_sources')),
    sa.PrimaryKeyConstraint('label_set_id', name=op.f('pk_fda_labels'))
    )
    op.create_table('food_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drug_id', sa.String(), nullable=True),
    sa.Column('food', sa.Text(), nullable=False),
    sa.Column('food_vi', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('mechanism_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('management', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], name=op.f('fk_food_interactions_drug_id_drugs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_food_interactions_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_interactions'))
    )
    op.create_index('ix_food_drug', 'food_interactions', ['drug_id'], unique=False)
    op.create_table('interaction_mechanisms',
    sa.Column('mechanism_id', sa.String(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('mechanism_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('management', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('n_pairs', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_interaction_mechanisms_source_id_sources')),
    sa.PrimaryKeyConstraint('mechanism_id', name=op.f('pk_interaction_mechanisms'))
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescription_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('drug_id', sa.String(), nullable=True),
    sa.Column('ingredient', sa.Text(), nullable=True),
    sa.Column('dose', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('norm_status', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], name=op.f('fk_medications_drug_id_drugs')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_medications_prescription_id_prescriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications'))
    )
    op.create_index(op.f('ix_medications_prescription_id'), 'medications', ['prescription_id'], unique=False)
    op.create_table('pk_ddi',
    sa.Column('perpetrator_id', sa.String(), nullable=False),
    sa.Column('victim_id', sa.String(), nullable=False),
    sa.Column('auc_fold_change', sa.Float(), nullable=True),
    sa.Column('magnitude', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['perpetrator_id'], ['drugs.drug_id'], name=op.f('fk_pk_ddi_perpetrator_id_drugs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_pk_ddi_source_id_sources')),
    sa.ForeignKeyConstraint(['victim_id'], ['drugs.drug_id'], name=op.f('fk_pk_ddi_victim_id_drugs')),
    sa.PrimaryKeyConstraint('perpetrator_id', 'victim_id', name=op.f('pk_pk_ddi'))
    )
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('registration_no', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('active_ingredients', sa.Text(), nullable=True),
    sa.Column('strength', sa.Text(), nullable=True),
    sa.Column('dosage_form', sa.Text(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('form_group', sa.Text(), nullable=True),
    sa.Column('enteric_coated', sa.Boolean(), nullable=False),
    sa.Column('modified_release', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('manufacturer_country', sa.Text(), nullable=True),
    sa.Column('registrant', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_products_source_id_sources')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_route'), 'products', ['route'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('drug_interactions',
    sa.Column('interaction_id', sa.BigInteger(), nullable=False),
    sa.Column('drug_a', sa.String(), nullable=False),
    sa.Column('drug_b', sa.String(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('mechanism_id', sa.String(), nullable=True),
    sa.Column('mechanism_type', sa.Text(), nullable=True),
    sa.Column('both_in_vn', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.CheckConstraint("severity IN ('contraindicated','major','moderate','minor')", name=op.f('ck_drug_interactions_ck_pair_severity')),
    sa.ForeignKeyConstraint(['drug_a'], ['drugs.drug_id'], name=op.f('fk_drug_interactions_drug_a_drugs')),
    sa.ForeignKeyConstraint(['drug_b'], ['drugs.drug_id'], name=op.f('fk_drug_interactions_drug_b_drugs')),
    sa.ForeignKeyConstraint(['mechanism_id'], ['interaction_mechanisms.mechanism_id'], name=op.f('fk_drug_interactions_mechanism_id_interaction_mechanisms')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_drug_interactions_source_id_sources')),
    sa.PrimaryKeyConstraint('interaction_id', name=op.f('pk_drug_interactions'))
    )
    op.create_index('ix_pair_ab', 'drug_interactions', ['drug_a', 'drug_b'], unique=False)
    op.create_index('ix_pair_mech', 'drug_interactions', ['drug_a', 'drug_b', 'mechanism_id'], unique=False)
    op.create_index('ix_pair_vn', 'drug_interactions', ['both_in_vn', 'severity'], unique=False)
    op.create_table('product_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.Text(), nullable=False),
    sa.Column('strength', sa.Text(), nullable=True),
    sa.Column('drug_id', sa.String(), nullable=True),
    sa.Column('base_drug_id', sa.Text(), nullable=True),
    sa.Column('match_method', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('route_match', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], name=op.f('fk_product_ingredients_drug_id_drugs')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_product_ingredients_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_ingredients')),
    sa.UniqueConstraint('product_id', 'position', 'drug_id', name='uq_prod_ing')
    )
    op.create_index('ix_prod_ing_drug', 'product_ingredients', ['drug_id'], unique=False)
    op.create_index(op.f('ix_product_ingredients_product_id'), 'product_ingredients', ['product_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescription_id', sa.String(), nullable=True),
    sa.Column('check_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], name=op.f('fk_reviews_check_id_checks')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_reviews_prescription_id_prescriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_index(op.f('ix_product_ingredients_product_id'), table_name='product_ingredients')
    op.drop_index('ix_prod_ing_drug', table_name='product_ingredients')
    op.drop_table('product_ingredients')
    op.drop_index('ix_pair_vn', table_name='drug_interactions')
    op.drop_index('ix_pair_mech', table_name='drug_interactions')
    op.drop_index('ix_pair_ab', table_name='drug_interactions')
    op.drop_table('drug_interactions')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_route'), table_name='products')
    op.drop_table('products')
    op.drop_table('pk_ddi')
    op.drop_index(op.f('ix_medications_prescription_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_table('interaction_mechanisms')
    op.drop_index('ix_food_drug', table_name='food_interactions')
    op.drop_table('food_interactions')
    op.drop_table('fda_labels')
    op.drop_table('duplication_classes')
    op.drop_table('dosage_form_rules')
    op.drop_index(op.f('ix_disease_interactions_drug_id'), table_name='disease_interactions')
    op.drop_table('disease_interactions')
    op.drop_index(op.f('ix_checks_prescription_id'), table_name='checks')
    op.drop_table('checks')
    op.drop_table('ara_interactions')
    op.drop_index('ix_aliases_drug', table_name='aliases')
    op.drop_table('aliases')
    op.drop_table('sources')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_drugs_in_vn'), table_name='drugs')
    op.drop_index('ix_drugs_base_name', table_name='drugs')
    op.drop_index('ix_drugs_atc', table_name='drugs')
    op.drop_table('drugs')
    # ### end Alembic commands ###
